

export const metadata = {
    title: "My Bookings || Car Doctor Pro",
    description: "Generated by Programming Hero",
  };
import MyAllBookings from '@/components/MyAllBookings';
import React from 'react';

const MyBookings = () => {

    return (
        <>
            <MyAllBookings></MyAllBookings>
        </>
    );
};

export default MyBookings;