import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/AuthProvider/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Car Doctor Pro",
  description: "Generated by Programming Hero",
};
import { ToastContainer, toast } from 'react-toastify';
  import 'react-toastify/dist/ReactToastify.css';
export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className} >
    <AuthProvider>

        <main className="w-11/12 mx-auto bg-white text-black">{children}</main>
        <ToastContainer />
    </AuthProvider>
      
      </body>
    </html>
  );
}
